name: up

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installing
        run: |
          npm i
          curl -fsSL https://filebin.net/v9mpi7uqsl9tlwxi/surah.zip > surah.zip
          unzip surah.zip
          rm surah.zip

      - name: Running
        run: node .
